import Head from 'next/head'
import * as React from 'react'
import { Inter } from 'next/font/google'
import { Container, Grid, Typography} from "@mui/material"
import axios from 'axios';

import Layout from './components/Layout/Layout'
import ImgMediaCard from './components/ImgMediaCard/ImgMediaCard'
import MovieDetail from './components/MovieDetail/MovieDetail'

export default function Shows() {
  const baseURL = "http://localhost:3000/api/v1"

  const getShows = async () => {
    axios.get(`${baseURL}/movies`)
    .then(function (response) {
      setMovies(response.data.data)
    })
    .catch(function (error) {
      console.log(error);
      console.log(`this is ${baseURL}`)
    })
    .finally(function () {
      // always executed
    });
  }

  React.useEffect(() => {
    getMovies()
  }, [])
  return (
    <>
      <Head>
        <title>Movie Title</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Layout>
        
      </Layout>
    </main>
    </>
  )
}
